### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Nbr1Sniper** [pyalarmdotcom/alarmdotcom#142]
After installing the integration in HACs I restarted my HA and tried to add the Alarm.com integration. It gave me a config error as undefined and wouldn’t continue.

**Comment by elahd** [comment]
Are you able to pull more detailed error logs? If you can't find anything, try adding the below to you configuration.yaml file, rebooting, and retrying setup. This will output debug-level logs from the integration.

```yaml
logger:
  default: warn
  logs:
    custom_components.alarmdotcom: debug
    pyalarmdotcomajax: debug
```
